### ISSUE TITLE
Suggestion: The pipeline is more important than the data modelling

### ISSUE THREAD

**Issue by jcii** [chaim1221/navaja-api#1]
I'm going to put suggestions here, for the lulz:

I suggest working on the pipeline and scaffolding before getting into the problem domain. Get the simplest thing possible up, like a static web page, then get it building in Travis and deploying w/ Chef or Docker. You know how to model data. So does everyone else. Get a push-button Build & Deploy pipeline up.

**Comment by chaim1221** [comment]
The simplest thing possible here will be an API endpoint. Problem is I don't really know how to do that in Node.js. It shouldn't be too long until I have a thin slice done on either end. The goal is continuous deployment. Probably not doing Docker right away, but I might do it with Chef.

**Comment by chaim1221** [comment]
Closing this as we are starting work on the pipeline.
